namespace RustComponent
{
    [default_interface]
    runtimeclass Sample
    {
        Sample();
        Sample(String greeting);
        
        String Greeting;

        void PrintGreeting();
    }
}
