[package]
name = "RustComponent"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.29.0"
features = [
    "build",
    "Win32_Foundation",
    "Win32_System_WinRT"
]

[build-dependencies]
cc = "1.0.72"
windows-bindgen = "0.29.0"

[lib]
crate-type = ["cdylib"]
